### ISSUE TITLE
Reconstructed_file.json: the ForensicActions and ProvenanceRecords need some review and rework

### ISSUE THREAD

**Issue by sbarnum** [casework/case#10]
I think the ForensicActions and ProvenanceRecords need some work:
    - The “object” of a forensic action should likely be a trace rather than a provenance record to be explicitly specific
    - The example is missing the “android_image” Trace which I think should be there
    - I don’t think provenance records should have other provenance records in their “object” list such as in “provenance_record1”. Provenance records should only be in the “result” list of forensic actions.
    - It seems like
        - forensic_action0 should have “object” = “android_image” and “result” = “provenance_record3” (and maybe “provenance_record4”??)
        - There should be a forensic_action1 for the reconstruction action with “object” = [“data_piece0”, “data_piece1”, “data_piece2”, “relationship3”, “relationship4”] and “result” = “provenance_record2”
        - It seems like provenance_record0 is unnecessary for the example and just confusing.
        - I do not see the purpose or need for provenance_record1 or provenance_record4

**Comment by casework** [comment]
> - The “object” of a forensic action should likely be a trace rather than a provenance record to be explicitly specific

The original rules discussed was that forensic actions can only point to provenance records or other forensic actions. If that needs to change, it should be brought up in a discussion. Both ForensicAction and ProvenanceRecord are not Traces and therefore should be called "object" (for lack of a better name).

> - The example is missing the “android_image” Trace which I think should be there

Added.

> - I don’t think provenance records should have other provenance records in their “object” list such as in “provenance_record1”. Provenance records should only be in the “result” list of forensic actions.

Fixed.

> - It seems like forensic_action0 should have “object” = “android_image” and “result” = “provenance_record3” (and maybe “provenance_record4”??)

- Going by the original rule that ForensicActions can only point to Traces through a ProvenanceRecord mediator, "object" points to a provenance record that then points to the "android_image"
- I moved the proventance records into "result" based on the previous fix. 

> - There should be a forensic_action1 for the reconstruction action with “object” = [“data_piece0”, “data_piece1”, “data_piece2”, “relationship3”, “relationship4”] and “result” = “provenance_record2”

It depends on how modularized the carving tool is. In this example, the tools does both the carving and reconstruction in a single black box procedure. Which unfortunately is more of a realistic situation. If the carving and reconstruction where different tools or modules, then yes we would have another forensic action for the reconstruction, separate from the carving. Let me know if you think we should change it anyway.

> - It seems like provenance_record0 is unnecessary for the example and just confusing.

Again, this goes back to the orignal rule I mentioned.

> - I do not see the purpose or need for provenance_record1 or provenance_record4

- provenance_record1 is gone now.
- For provenance_record4, I was trying to show how data_piece0 (the JPG header) is different than the other pieces because this was data that was not actually carved out of the image. This header was generated by the reconstruction algorithm to be appended to the file because the original header was missing. I figured it should have a different exhibit number because it's data that did not originate from the evidence. _(I'm not sure if this is the best way to do it. We should get an expert on this to weigh in on this.)_

**Comment by sbarnum** [comment]
> The original rules discussed was that forensic actions can only point to provenance records or other forensic actions. If that needs to change, it should be brought up in a discussion. 

This is not my recollection of the original rules discussed.
In the original discussion the rule agreed to was that Forensic Actions (FAs) would always **OUTPUT** only Provenance Records (PRs) or other FAs but no such restrictions were placed on the input for the actions (i.e., what the action is acting on).
I believe the physical forensics corollary we discussed was a forensic evidence label that is applied to each piece of evidence collected or generated (through examination or analysis) and explicitly captures "where" that evidence came from. So, in all forensic actions in the physical world you have pieces of evidence and you have evidence labels that tie them back to the actions they came from.
This is the same thing as having Traces and having PRs that tie those Traces back to the FA that they came from.
Just like in physical world forensics where a new forensic action (examination or analysis) is performed on the actual evidence and not on the evidence label, the same should be true in the digital sphere where an FA acts on ("object" list) the evidence itself (Traces, etc) and not on a PR label associated with that evidence. The PR forms the link backward in the provenance chain not forward.
To me, this is the only way that makes sense in pure semantics and in the technical details as well. 

An approach where all input to FAs is PRs would require that every Trace out of any previous FA would need a separate PR (a HUGE inefficiency and complexity) as you never know which Trace out of one FA may be the object of a future FA and grouping multiple Traces under a single PR (which makes complete sense for many FAs) would not give enough specificity to determine which of the multiple Traces the future FA was actually acting on. I believe this unnecessary complexity is demonstrated in the example by requiring extraneous PRs and such whose only purpose appears to be to comply with an approach where only PRs are input for FAs.

Simply making FAs act on ("object" list) the Traces themselves and output ("result" list) PRs avoids this complexity, aligns to the physical world corollary and just makes more sense to me.

>> - There should be a forensic_action1 for the reconstruction action with “object” = [“data_piece0”, “data_piece1”, “data_piece2”, “relationship3”, “relationship4”] and “result” = “provenance_record2”

>It depends on how modularized the carving tool is. In this example, the tools does both the carving and reconstruction in a single black box procedure. Which unfortunately is more of a realistic situation. If the carving and reconstruction where different tools or modules, then yes we would have another forensic action for the reconstruction, separate from the carving. Let me know if you think we should change it anyway.

While it may be the same tool doing both actions, I would suggest that it is still two separate actions (with different inputs, outputs and purposes) being performed and it would make more sense to explicitly capture each action separately. This allows significantly more clarity into what all the tool is doing and also more clarity into the various pieces of evidence and PRs involved. If ToolA can do Action1 and Action2 that is great but someone receiving the evidence may wish to carry out Action2 again using a different tool and having everything lumped together would make this very difficult.

I would strongly suggest that FAs should be based on what action they are representing and not on what tool is being used. The "instrument" for the action is secondary to the action itself.
