### ISSUE TITLE
Versioning for CASE

### ISSUE THREAD

**Issue by jstroud-mitre** [casework/CASE#2]
Moving forward, once CASE is exposed as an RDF endpoint I believe following [OWL's recommendation for ontology versioning](https://www.w3.org/TR/owl2-syntax/#Versioning_of_OWL_2_Ontologies) makes sense.

Thoughts?

**Comment by asovern-mitre** [comment]
It appears that owl:versionInfo is also referenced by [OWL's Web Ontology Language](https://www.w3.org/TR/owl-ref/#Header)

**Comment by ajnelson-nist** [comment]
What do you picture as a code resolution to this Issue?  Would any of the examples in this repository receive an update?

**Comment by jstroud-mitre** [comment]
I believe having something like [Apache Jena Fuseki](https://jena.apache.org/documentation/fuseki2/) (or any other web server) publicly accessible on the internet will server CASE/UCO RDF.

An example URL could be http://<case_url>.org/v1/#core

Supporting documents for serving RDF found [here](https://www.w3.org/TR/swbp-vocab-pub/).

**Comment by regriff** [comment]
We need to ensure we are addressing how implementors utilize our namespace for versioning, with consideration for replicating previous results based on previous iterations of the ontology. CASE exports should reference the specific version of the standard (through a direct reference to the version's namespace) so that results can be reproduced in the future. This consideration would also restrict implementors from referencing the base namespace URL, which would not specify a particular version of the standard.

**Comment by ajnelson-nist** [comment]
This was implemented in [UCO Issue 437](https://github.com/ucoProject/UCO/issues/437), part of the CASE 0.9.1 and 1.0.0 releases.  I'm closing this issue as duplicated and resolved.
