### ISSUE TITLE
Email link in readme is wrong

### ISSUE THREAD

**Issue by cugu** [casework/CASE#27]
The "Email" in the README.md is not existent (any more).

**Comment by ajnelson-nist** [comment]
Ah, thank you!  We'll update this.

**Comment by ajnelson-nist** [comment]
Ah, I misunderstood, thinking you were reporting a broken link to an email address.  The examples are being moved to an independent repository within the next few days; their current state is in [this branch](https://github.com/casework/CASE/tree/examples-post-v0.1-formalization-to-uco).

**Comment by ajnelson-nist** [comment]
We are tracking this on CASE's Jira, ONT-240.

**Comment by cugu** [comment]
I was referring to `- [Email](examples/email.json)`

**Comment by cugu** [comment]
It's also wrong in the branch ;-)

**Comment by ajnelson-nist** [comment]
@cugu Thanks for the report.  The link is fixed in the branch that will be migrating off, so I'll be closing this issue.  I admit it looks a bit odd leaving the error in `master`, but since the last update to `master`, we've adopted a different development model that makes revisions to `master` require a bit more in review mechanics and versioning implications.
